name: Manual PR Approval

on:
  pull_request:
    types: [labeled]  # Trigger when a label is added to the PR

jobs:
  approve-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for 'tested' label
        run: |
          # Check if the label is 'tested'
          if [[ "${{ github.event.label.name }}" == "tested" ]]; then
            echo "Found 'tested' label, allowing merge."
            exit 0  # Workflow passes, enabling merge
          else
            echo "No 'tested' label found, blocking merge."
            exit 1  # Workflow fails, preventing merge
          fi
