name: Manual PR Approval

on:
  pull_request:
    types: [labeled, unlabeled]  # Trigger when a label is added or removed from the PR

jobs:
  approve-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for 'tested' label
        run: |
          # Get the current list of labels for the PR
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels")
          
          # Check if the 'tested' label is present
          if echo "$LABELS" | grep -q '"name": "tested"'; then
            echo "Found 'tested' label, allowing merge."
            exit 0  # Workflow passes, enabling merge
          else
            echo "No 'tested' label found, blocking merge."
            exit 1  # Workflow fails, preventing merge
          fi
